name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: "8.6.1"
      #Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "^19.0.0"
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run generate
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          local-dir: ./dist/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
